### ISSUE TITLE
Different results with different mss.

### ISSUE THREAD

**Issue by E-11-V** [ryanfb/bl-dl#1]
Hi,

I have finally managed to use bl-dl but I cannot figure out why I am getting different results with different mss. While the one in the README works just fine, when I run it with https://www.bl.uk/manuscripts/Viewer.aspx?ref=lansdowne_ms_762_fs001r I get spotty results
![image](https://user-images.githubusercontent.com/84926127/205098449-be709e12-582c-4541-9711-d89d31ece4c5.png)
 and the following error messages 
![image](https://user-images.githubusercontent.com/84926127/205099530-4f723e91-b74d-49ea-96ec-f7661dded8b8.png)
Any ideas? My guess is that it has to do with how they were digitised in the first place but I actually know nothing tech-wise... Than you for your help!

**Comment by ryanfb** [comment]
Thanks for bringing this to my attention! I've seen this issue with some other image servers, likely the issue is with how the tiles are stored/served on the British Library's end. Increasing the timeout and number of retries passed to `dezoomify-rs` seemed to fix the issue for me, so I'll push a fix with that.

If you're accessing via Docker, you may need to run `docker pull ryanfb/bl-dl` once https://hub.docker.com/r/ryanfb/bl-dl is updated to get the updated code before re-running with `docker run`.
